TMP_DIR = "tmp"
DATA_DIR = "data"
COLLECTION_DIR = "collection"
LABEL_DIR = "label"
RESULT_DIR = "result"
COUGH = "cough"
MOUTH = "mouth"
NOSE = "nose"
BAD = "bad"
GOOD = "good"
LOCK = "lock"
UNLOCK = "unlock"
S3_AUDIO_EXTRA_PARAM = {"ContentType": 'audio/wav'}
S3_JSON_EXTRA_PARAM = {"ContentType": 'application/json'}
S3_IMAGE_EXTRA_PARAM = {"ContentType": 'image/jpeg'}
ENABLE_AUDIO_FILTER = 1
DISABLE_AUDIO_FILTER = 0
